# Generated by Django 3.0.4 on 2020-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
