# Generated by Django 3.0.4 on 2020-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_a_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
