# Generated by Django 3.0.4 on 2020-03-23 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_a_room',
            name='date_booked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
