# Generated by Django 3.0.4 on 2020-03-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_book_a_room_date_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_a_room',
            name='date_booked',
        ),
    ]
