# Generated by Django 3.0.4 on 2020-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_book_a_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_a_room',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
