# Generated by Django 3.0.4 on 2020-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200325_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_a_room',
            name='roomtype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
