# Generated by Django 3.0.4 on 2020-03-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_book_a_room_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_a_room',
            name='roomtype',
        ),
    ]
