# Generated by Django 3.0.4 on 2020-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_book_a_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_a_room',
            name='roomtype',
            field=models.CharField(blank=True, choices=[('Superior room', 'Superior room'), ('Premier room', 'Premier room'), ('Deluxe Suite', 'Deluxe Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=30, null=True),
        ),
    ]
